name: Nuclei Action
on: push
jobs:  
  dast:
    name: Scan API Endpoints
    runs-on: ubuntu-latest    
    steps:
      - uses: actions/checkout@v2

      - name: Start application
        run: docker run -d -p 5050:5050 --name flask we45/vul_flask

      # - name: DAST Scan
      #   uses: projectdiscovery/nuclei-action@main
      #   with:
      #     target: http://localhost:5050
      #     templates: ./api-scan.yaml

      - name: Template Injection
        uses: projectdiscovery/nuclei-action@main
        with:
          target: http://localhost:5050
          templates: ./template-injection.yaml

      - name: GitHub Security Dashboard Alerts
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: nuclei.sarif

      - name: Stop application
        if: always()
        run: docker stop flask
      
      