name: Nuclei Action
on: push
jobs:  
  dast:
    name: Scan API Endpoints
    runs-on: ubuntu-latest    
    steps:
      - uses: actions/checkout@v2

      - name: Start application
        #run: docker run -d -p 5050:5050 --name flask we45/vul_flask
        run: docker run -d -p 3000:3000 grafana/grafana-enterprise:8.1.0

      - name: Template Injection
        uses: projectdiscovery/nuclei-action@main
        with:
          #target: http://localhost:5050
          target: http://localhost:3000
          templates: ./CVE-2021-41174.yaml
          #templates: ./template-injection.yaml

      - name: Stop application
        if: always()
        run: docker stop flask
      
      
